In [1]:

import pandas as pd

In [2]:
!pip install tensorflow

  Using cached tensorflow-2.20.0-cp312-cp312-win_amd64.whl.metadata (4.6 kB)
  Using cached keras-3.11.3-py3-none-any.whl.metadata (5.9 kB)
  Using cached rich-14.1.0-py3-none-any.whl.metadata (18 kB)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Using cached tensorflow-2.20.0-cp312-cp312-win_amd64.whl (331.9 MB)
Using cached keras-3.11.3-py3-none-any.whl (1.4 MB)
Using cached rich-14.1.0-py3-none-any.whl (243 kB)
Using cached markdown_it_py-4.0.0-py3-none-any.whl (87 kB)


In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
df=pd.read_csv('binary_classification.csv')

In [8]:
df.head(3)

input_1   input_2   input_3   input_4   input_5   input_6   input_7  \
0  0.496714 -0.138264  0.647689  1.523030 -0.234153 -0.234137  1.579213   
1  0.767435 -0.469474  0.542560 -0.463418 -0.465730  0.241962 -1.913280   
2 -1.724918 -0.562288 -1.012831  0.314247 -0.908024 -1.412304  1.465649   

   output  
0     1.0  
1     0.0  
2     0.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   input_1  2000 non-null   float64
 1   input_2  2000 non-null   float64
 2   input_3  2000 non-null   float64
 3   input_4  2000 non-null   float64
 4   input_5  2000 non-null   float64
 5   input_6  2000 non-null   float64
 6   input_7  2000 non-null   float64
 7   output   2000 non-null   float64
dtypes: float64(8)
memory usage: 125.1 KB


In [10]:
df.shape

(2000, 8)

In [11]:
df.describe()

input_1      input_2      input_3      input_4      input_5  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean     -0.011210     0.006434     0.017266    -0.019354    -0.045741   
std       0.985840     1.010564     1.007568     1.012431     1.012373   
min      -3.221016    -3.375579    -3.688365    -3.836656    -3.241514   
25%      -0.667445    -0.657998    -0.655159    -0.733670    -0.704931   
50%       0.008332     0.006202     0.029813    -0.039674    -0.060248   
75%       0.639939     0.685866     0.700306     0.654006     0.634214   
max       3.098299     2.985259     3.428910     3.529055     3.926238   

           input_6      input_7       output  
count  2000.000000  2000.000000  2000.000000  
mean      0.036013     0.016710     0.504500  
std       1.013294     0.966612     0.500105  
min      -3.922400    -2.908661     0.000000  
25%      -0.627159    -0.636369     0.000000  
50%       0.045498     0.011523     1.000000  
75%       0.702565     0.655533     1.000000  
max       3.377768     3.852731     1.000000

In [12]:
df.describe().T

count      mean       std       min       25%       50%       75%  \
input_1  2000.0 -0.011210  0.985840 -3.221016 -0.667445  0.008332  0.639939   
input_2  2000.0  0.006434  1.010564 -3.375579 -0.657998  0.006202  0.685866   
input_3  2000.0  0.017266  1.007568 -3.688365 -0.655159  0.029813  0.700306   
input_4  2000.0 -0.019354  1.012431 -3.836656 -0.733670 -0.039674  0.654006   
input_5  2000.0 -0.045741  1.012373 -3.241514 -0.704931 -0.060248  0.634214   
input_6  2000.0  0.036013  1.013294 -3.922400 -0.627159  0.045498  0.702565   
input_7  2000.0  0.016710  0.966612 -2.908661 -0.636369  0.011523  0.655533   
output   2000.0  0.504500  0.500105  0.000000  0.000000  1.000000  1.000000   

              max  
input_1  3.098299  
input_2  2.985259  
input_3  3.428910  
input_4  3.529055  
input_5  3.926238  
input_6  3.377768  
input_7  3.852731  
output   1.000000

In [13]:
df.isna().sum()

input_1    0
input_2    0
input_3    0
input_4    0
input_5    0
input_6    0
input_7    0
output     0
dtype: int64

In [14]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
# 'X' contains all columns except for 'output'
X = df.drop('output', axis=1)

# 'y' contains only the 'output' column
y = df['output']

In [17]:
X

input_1   input_2   input_3   input_4   input_5   input_6   input_7
0     0.496714 -0.138264  0.647689  1.523030 -0.234153 -0.234137  1.579213
1     0.767435 -0.469474  0.542560 -0.463418 -0.465730  0.241962 -1.913280
2    -1.724918 -0.562288 -1.012831  0.314247 -0.908024 -1.412304  1.465649
3    -0.225776  0.067528 -1.424748 -0.544383  0.110923 -1.150994  0.375698
4    -0.600639 -0.291694 -0.601707  1.852278 -0.013497 -1.057711  0.822545
...        ...       ...       ...       ...       ...       ...       ...
1995 -0.173815  0.995955  0.736227 -0.983103 -1.010591 -0.254374  0.736837
1996  0.148057 -0.643150  0.261519 -0.330811  0.880486  0.333058 -0.315278
1997  0.231519  1.315048 -0.569630  0.402657 -0.070460  0.426984 -0.654565
1998  0.110335  1.107823 -0.937007 -1.329405 -1.291456 -1.170663  0.595323
1999 -1.405860 -0.297895  0.618289  0.416659 -0.385559  0.190924  0.107145

[2000 rows x 7 columns]

In [18]:
y

0       1.0
1       0.0
2       0.0
3       0.0
4       1.0
       ... 
1995    1.0
1996    1.0
1997    1.0
1998    0.0
1999    0.0
Name: output, Length: 2000, dtype: float64

In [19]:
X= df.iloc[:,0:-1]
y= df.iloc[:,-1]

In [20]:
X.head(5)

input_1   input_2   input_3   input_4   input_5   input_6   input_7
0  0.496714 -0.138264  0.647689  1.523030 -0.234153 -0.234137  1.579213
1  0.767435 -0.469474  0.542560 -0.463418 -0.465730  0.241962 -1.913280
2 -1.724918 -0.562288 -1.012831  0.314247 -0.908024 -1.412304  1.465649
3 -0.225776  0.067528 -1.424748 -0.544383  0.110923 -1.150994  0.375698
4 -0.600639 -0.291694 -0.601707  1.852278 -0.013497 -1.057711  0.822545

In [21]:
y.head(4)

0    1.0
1    0.0
2    0.0
3    0.0
Name: output, dtype: float64

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=42)

In [23]:

from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

In [24]:
X_train=sc.fit_transform(X_train)
X_train

array([[ 0.88171296,  0.31229879,  0.79977687, ...,  1.2166301 ,
        -0.01250636,  0.03508656],
       [ 0.4106209 , -0.03267114, -0.89642315, ..., -1.13295989,
         1.14838849, -0.50228145],
       [-0.18694097, -0.57740697, -0.28523484, ...,  1.42395623,
        -0.63971559,  0.07732647],
       ...,
       [ 0.25546268,  0.38678617,  2.43734569, ..., -0.28303275,
         0.09363827,  1.07761968],
       [-0.10817496, -1.90411904, -0.95664478, ..., -2.67376728,
         1.1481401 ,  0.51165485],
       [ 1.29749779, -0.06522895,  0.12975408, ...,  1.18577221,
        -1.65111788,  0.5767523 ]], shape=(1600, 7))

In [25]:
X_test=sc.transform(X_test)
X_test

array([[-0.15551846,  0.99475181, -0.18549756, ...,  0.16253762,
         1.02441568,  0.80375679],
       [ 2.38193209, -0.78732539, -1.36503441, ...,  0.74259226,
        -0.24850278,  1.47024117],
       [-0.30688516, -0.57780731,  0.84650587, ..., -0.15432125,
         1.34905633, -0.24271779],
       ...,
       [-0.54130144, -1.92297251, -0.3330173 , ..., -0.82956279,
        -1.51866793,  0.3706796 ],
       [ 1.42356217, -0.10636679,  0.00925317, ...,  0.26068234,
         0.9174261 ,  0.27087882],
       [-0.17794699, -2.16537327,  0.16596034, ..., -1.42416288,
        -0.59814396,  0.31405761]], shape=(400, 7))

In [26]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [27]:
classifier= Sequential()

In [28]:
classifier.add(Dense(units= 5, kernel_initializer='he_uniform', activation='relu', input_dim=7))
classifier.add(Dense(units= 5, kernel_initializer='he_uniform', activation='relu'))
classifier.add(Dense(units=1, kernel_initializer='glorot_uniform', activation='sigmoid'))

c:\genAI\venv-genAI\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [29]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [30]:
Model_history= classifier.fit(X_train, y_train, validation_split=0.33,batch_size= 10, epochs= 100,verbose=1)

Epoch 1/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6968 - loss: 0.6063 - val_accuracy: 0.7235 - val_loss: 0.5858
Epoch 2/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7547 - loss: 0.5389 - val_accuracy: 0.7557 - val_loss: 0.5229
Epoch 3/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7957 - loss: 0.4724 - val_accuracy: 0.7841 - val_loss: 0.4651
Epoch 4/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8218 - loss: 0.4145 - val_accuracy: 0.8011 - val_loss: 0.4167
Epoch 5/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8451 - loss: 0.3704 - val_accuracy: 0.8258 - val_loss: 0.3800
Epoch 6/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8517 - loss: 0.3406 - val_accuracy: 0.8409 - val_loss: 0.3542
Epoch 7/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8647 - loss: 0.3215 - val_accuracy: 0.8504 - val_loss: 0.3360
Epoch 8/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8666 - loss: 0.3093 - val_accu

In [31]:
classifier.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 5)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 230 (924.00 B)

 Trainable params: 76 (304.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 154 (620.00 B)

In [32]:
y_pred = classifier.predict(X_test)
y_pred

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


array([[9.98108864e-01],
       [9.88164604e-01],
       [9.68948901e-01],
       [3.15274298e-01],
       [9.87193704e-01],
       [7.52355278e-01],
       [9.95961607e-01],
       [4.69109625e-01],
       [5.04738502e-02],
       [1.13080502e-01],
       [4.85434175e-01],
       [8.32697153e-01],
       [3.98338169e-01],
       [9.80146170e-01],
       [9.97742474e-01],
       [1.68659106e-01],
       [9.20359075e-01],
       [7.79991567e-01],
       [8.02685246e-02],
       [9.59377643e-03],
       [9.87639785e-01],
       [9.87026215e-01],
       [9.72739041e-01],
       [9.54310358e-01],
       [1.80367216e-01],
       [7.63894677e-01],
       [9.88172829e-01],
       [5.81151014e-03],
       [6.06630921e-01],
       [9.98373449e-01],
       [8.53769541e-01],
       [9.80707347e-01],
       [1.20250415e-02],
       [1.73883244e-01],
       [1.00915115e-02],
       [1.11791473e-04],
       [9.98472273e-01],
       [1.48801893e-01],
       [9.87658978e-01],
       [5.15835127e-03],


In [33]:
y_pred2 = [1 if y>=0.5 else 0 for y in y_pred]
print(y_pred2)


[1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 

In [34]:
y_pred2 = [1 if y>=0.5 else 0 for y in y_pred]
y_pred2



[1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,


In [35]:
from sklearn.metrics import accuracy_score

In [36]:
accuracy_score(y_test, y_pred2)

0.8775

In [39]:

Loss,Accuracy= classifier.evaluate(X_test,y_test)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8775 - loss: 0.2680 


In [43]:
loss, accuracy = classifier.evaluate(X_test, y_test, verbose=0)

In [44]:
print(f"LOSS:{loss:.4f}")
print(f"Accuracy:{Accuracy*100:.2f}%")

LOSS:0.2680
Accuracy:87.75%


In [47]:
from sklearn.metrics import classification_report, confusion_matrix

# It's good practice to get the raw probabilities from the model first
y_pred_probabilities = classifier.predict(X_test)

# IMPORTANT: Convert probabilities into final 0 or 1 predictions
y_pred_final = (y_pred_probabilities > 0.5).astype(int)

# Now, use the final binary predictions in your reports
print("\nClassification Report:")
print(classification_report(y_test, y_pred_final))

print("\nConfusion Matrix:")
conf_matrix = confusion_matrix(y_test, y_pred_final)
print(conf_matrix)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 

Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.87      0.88       204
         1.0       0.87      0.89      0.88       196

    accuracy                           0.88       400
   macro avg       0.88      0.88      0.88       400
weighted avg       0.88      0.88      0.88       400


Confusion Matrix:
[[177  27]
 [ 22 174]]
